version: '2'


services:
    web:
        image: julitom1/connectiondb
        container_name: web
        ports:
            - "42000:6000"
    web2:
        image: julitom1/connectiondb
        container_name: web2
        ports:
            - "42001:6000"
    web3:
        image: julitom1/connectiondb
        container_name: web3
        ports:
            - "42002:6000"
    web4:
        image: julitom1/roundrobin
        container_name: web4
        ports:
            - "45000:6000"
    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        
volumes:
    mongodb:
    mongodb_config:
